notifications:
  email: false
  slack: false

language: node_js

node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn
  - yarn dev